/*
 * HMap.java
 *
 * Created on August 30, 2008, 2:08 PM
 */
package Hexagonal;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  Joe Johnston
 */
public class HMap extends javax.swing.JFrame {
    int cycle = 0;
    int currX = 0;
    int currY = 0;
    int flatSideWidth=100;
    HexMap map;
    
    Color[] myColors = {Color.BLUE, Color.GREEN, Color.RED};
    
    /** Creates new form HMap */
    public HMap() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMain = new javax.swing.JPanel();
        bOK = new javax.swing.JButton();
        cbWidth = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lSize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        cbWidth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "125", "171" }));
        cbWidth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbWidthItemStateChanged(evt);
            }
        });
        cbWidth.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbWidthPropertyChange(evt);
            }
        });

        jLabel1.setText("Current hex size:");

        lSize.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(cbWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bOK)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSize)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOK)
                    .addComponent(cbWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lSize))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
    DrawPoly(currX, currY);
    currX += 10;
    currY += 10;
    cycle++;
    
}//GEN-LAST:event_bOKActionPerformed

private void updateSize() {
    String w = (String) cbWidth.getSelectedItem();
    flatSideWidth = Integer.valueOf(w);
    lSize.setText(w);    
}

private void cbWidthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbWidthPropertyChange
    // TODO add your handling code here:
}//GEN-LAST:event_cbWidthPropertyChange

private void cbWidthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbWidthItemStateChanged
// TODO add your handling code here:
    updateSize();
}//GEN-LAST:event_cbWidthItemStateChanged

    private void DrawPoly(int x, int y) {
        Graphics g = pMain.getGraphics();
        g.setColor(myColors[cycle % 3]);

        int A = flatSideWidth;
        int R = A / 2;
        int S = (int) Math.round(R / 0.866);  // COS30

        int H = (int) Math.round(0.5 * S);
        int B = (int) Math.round(S + 2 * H);

        Polygon P = new Polygon();
        // Vertex 0: NW
        P.addPoint(x + H, y);
        // Vertex 1: NE
        P.addPoint(x + B - H, y);
        // Vertex 2: E
        P.addPoint(x + B, y + R);
        // Vertex 3: SE
        P.addPoint(x + B - H, y + A);
        //Vertex 4: SW
        P.addPoint(x + H, y + A);
        // Vertex 5: W
        P.addPoint(x, y + R);

        //g.drawPolygon(P);
        g.fillPolygon(P);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOK;
    private javax.swing.JComboBox cbWidth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lSize;
    private javax.swing.JPanel pMain;
    // End of variables declaration//GEN-END:variables
}
